### ISSUE TITLE
Feature #1: Individual timetable page

### ISSUE THREAD

**Issue by NhatMinh0208** [NhatMinh0208/timetable-together#6]
What it says on the title.

## Tasks
- [x] Search bar for adding events
- [x] Right-side card: Show current events
- [x] Change schedule on right side card
- [x] Remove event on right side card
- [x] Middle calendar: show events
- [x] Change schedule on middle calendar
- [x] Change calendar view
